
export const ADD_TO_CART = "ADD_TO_CART";
export const INITIAL_COUNT ="INITIAL_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOTAL_PRICE_AND_QUANTITY = "TOTAL_PRICE_AND_QUANTITY";
export const DECREASE_CART = "DECREASE_CART";
export const INCREASE_CART = "INCREASE_CART";
